{
    "name": "Cancel LogNote",
    "version": "17.0.1.0.1",
    "summary": "",
    "description": "Cancel LogNote",
    "author": "Cybernetics+",
    "website": "https://www.cybernetics.plus",
    "live_test_url": "https://www.cybernetics.plus",
    "category": "Customizations",
    "license": "Other proprietary",
    "price": 999999999.99,
    "currency": "EUR",
    "installable": True,
    "application": False,
    "auto_install": False,
    "depends": ["web_studio"],
    "data": [
        'data/mail_templates.xml',
    ],
}