from . import account_pp30
from . import account_pnd54
from . import account_pp36
from . import account_pnd1
from . import account_pnd1g
from . import account_pnd3
from . import account_pnd53
from . import res_partner
from . import account_attach_pnd1g
