{
    "name": "Account Invoice",
    "version": "17.0.1.0.1",
    "summary": "Account Invoice",
    "description": "Account Invoice",
    "author": "Cybernetics+",
    "website": "https://www.cybernetics.plus",
    "live_test_url": "https://www.cybernetics.plus",
    "category": "CTP",
    "price": 999999999.99,
    "currency": "EUR",
    "installable": True,
    "application": False,
    "auto_install": False,
    "contributors": [
        "C+ Developer <dev@cybernetics.plus>",
    ],
    "depends": [
        "account",
        "account_accountant",
        "contacts",
        "ctp_partner_local_secondary",
    ],
    "data": [
        "security/ir.model.access.csv",
        "views/account_pp30_view.xml",
        "views/account_pnd54_view.xml",
        "views/account_pp36_view.xml",
        "views/account_pnd1_view.xml",
        "views/account_pnd1g_view.xml",
        "views/account_pnd3_view.xml",
        "views/account_pnd53_view.xml",
        "views/account_attach_pnd1g_view.xml",
        "views/res_partner_view.xml",
        "reports/account_pnd1_report.xml",
        "reports/account_pnd1g_report.xml",
        "reports/account_pnd54_report.xml",
        "reports/account_pnd30_report.xml",
        "reports/account_pnd36_report.xml",
        "reports/account_pnd3_report.xml",
        "reports/account_pnd53_report.xml",
        "reports/account_attach_pnd1g_report_action.xml",
    ],
        "assets": {
        "web.assets_qweb": [
            "account_invoice/static/src/scss/account_invoice.scss",
        ],
        "web.report_assets_common": [
            "account_invoice/static/src/scss/account_invoice.scss",
        ],
    },
}